In [1]:
import numpy as np

In [ ]:
# Why numpy?
# A lot of numpy functions are written in C, which is much faster than using python Lists or other native python functions
# It allows vectorization via broadcasting instead of running loops, which are much slower
# NumPy is also the backbone of other python packages such as Pandas

# NumPy stands for "Numeric Python"

# DataTypes & Attributes

In [7]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5 ,6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size # Total number of elements

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a dataframe from NumPy array
# So, we can also manipulate data in NumPy array using pandas, as needed

import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [11]:
sample_array = np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [14]:
type(ones)

numpy.ndarray

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0,10,(3,5))
random_array

array([[4, 9, 7, 2, 4],
       [3, 0, 7, 1, 8],
       [0, 2, 7, 4, 0]])

In [22]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.73882541, 0.06384392, 0.47925957],
       [0.36183663, 0.31505995, 0.49811896],
       [0.291404  , 0.95488121, 0.44013034],
       [0.45252515, 0.66545377, 0.44462307],
       [0.18513067, 0.18170803, 0.27007205]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3
# Every time we execute this, we get different set of numbers.

array([[0.35599872, 0.08673658, 0.36694492],
       [0.39738187, 0.8931959 , 0.86973786],
       [0.33151284, 0.87255103, 0.68912628],
       [0.517622  , 0.64043958, 0.53365491],
       [0.01276011, 0.68755756, 0.30891367]])

In [33]:
# Reproducible pseudo-random numbers by setting seed
np.random.seed(177)
random_array_4 = np.random.randint(0,10,(5,3))
random_array_4

# Every time we execute this, we get same set of numbers for a fixed seed.

array([[1, 7, 6],
       [4, 1, 5],
       [9, 2, 4],
       [4, 7, 9],
       [8, 1, 6]])

# Viewing Arrays and Matrices

In [34]:
np.unique(random_array_4) # Get unique elements of an array

array([1, 2, 4, 5, 6, 7, 8, 9])

In [35]:
a1[0]

1

In [36]:
a2[0]

array([1. , 2. , 3.3])

In [38]:
a2[1]

array([4. , 5. , 6.5])

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 4, 8, 3],
         [1, 1, 4, 1, 0],
         [8, 4, 3, 5, 0],
         [5, 7, 8, 5, 5]],

        [[0, 6, 7, 7, 2],
         [3, 4, 4, 6, 7],
         [3, 6, 4, 0, 1],
         [9, 3, 6, 2, 1]],

        [[3, 4, 5, 2, 5],
         [2, 8, 4, 0, 2],
         [4, 4, 4, 8, 8],
         [3, 9, 9, 9, 2]]],


       [[[9, 9, 3, 0, 4],
         [7, 4, 7, 3, 9],
         [7, 0, 4, 0, 8],
         [8, 0, 7, 1, 9]],

        [[8, 9, 4, 6, 4],
         [6, 4, 5, 7, 8],
         [6, 3, 8, 1, 2],
         [0, 9, 8, 1, 9]],

        [[9, 7, 0, 1, 3],
         [8, 9, 9, 5, 2],
         [7, 6, 8, 4, 3],
         [6, 6, 7, 2, 7]]]])

In [42]:
# Get the first 4 numbers of the inner-most array
a4[:,:,:,:4]

array([[[[3, 5, 4, 8],
         [1, 1, 4, 1],
         [8, 4, 3, 5],
         [5, 7, 8, 5]],

        [[0, 6, 7, 7],
         [3, 4, 4, 6],
         [3, 6, 4, 0],
         [9, 3, 6, 2]],

        [[3, 4, 5, 2],
         [2, 8, 4, 0],
         [4, 4, 4, 8],
         [3, 9, 9, 9]]],


       [[[9, 9, 3, 0],
         [7, 4, 7, 3],
         [7, 0, 4, 0],
         [8, 0, 7, 1]],

        [[8, 9, 4, 6],
         [6, 4, 5, 7],
         [6, 3, 8, 1],
         [0, 9, 8, 1]],

        [[9, 7, 0, 1],
         [8, 9, 9, 5],
         [7, 6, 8, 4],
         [6, 6, 7, 2]]]])

# Manipulating and Comparing Arrays

## Arithmatic

In [9]:
a1

array([1, 2, 3])

In [3]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [4]:
a1+ones

array([2., 3., 4.])

In [5]:
a1 - ones

array([0., 1., 2.])

In [6]:
a1 * ones

array([1., 2., 3.])

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
a1*a2 # broadcasting

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [12]:
a2*a3 # throws error because broadcasting has some rules

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

From: https://numpy.org/doc/stable/user/basics.broadcasting.html

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1

In [16]:
# So, let's reshape a2 to make broadcasting operation compatible
a2_new = np.expand_dims(a2,axis=-1)
a2_new

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [17]:
a2_new.shape

(2, 3, 1)

In [20]:
a3.shape

(2, 3, 3)

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
a2_new*a3 # Now it's allowed because last dimension of a2_new is 1 and other dimensions match with a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [21]:
a1/ones

array([1., 2., 3.])

In [23]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [22]:
a2 // a1 # floor division

array([[1., 1., 1.],
       [4., 2., 2.]])

In [24]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [25]:
# Numpy also has arithmatic functions for the same operations above
# Numpy functions are much faster when working with vectors and matrices

np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [26]:
np.add(a1,ones)

array([2., 3., 4.])

In [27]:
np.subtract(a1,ones)

array([0., 1., 2.])

In [28]:
np.multiply(a1,a2)

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [29]:
np.divide(a2,a1)

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [30]:
np.floor_divide(a2,a1)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [31]:
a1 % 2

array([1, 0, 1])

In [32]:
np.mod(a1,2)

array([1, 0, 1])

In [33]:
a1 / 2

array([0.5, 1. , 1.5])

In [34]:
np.divide(a1, 2)

array([0.5, 1. , 1.5])