In [2]:
import numpy as np

In [ ]:
# Why numpy?
# A lot of numpy functions are written in C, which is much faster than using python Lists or other native python functions
# It allows vectorization via broadcasting instead of running loops, which are much slower
# NumPy is also the backbone of other python packages such as Pandas

# NumPy stands for "Numeric Python"

# DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5 ,6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size # Total number of elements

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a dataframe from NumPy array
# So, we can also manipulate data in NumPy array using pandas, as needed

import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [11]:
sample_array = np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [14]:
type(ones)

numpy.ndarray

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0,10,(3,5))
random_array

array([[4, 9, 7, 2, 4],
       [3, 0, 7, 1, 8],
       [0, 2, 7, 4, 0]])

In [22]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.73882541, 0.06384392, 0.47925957],
       [0.36183663, 0.31505995, 0.49811896],
       [0.291404  , 0.95488121, 0.44013034],
       [0.45252515, 0.66545377, 0.44462307],
       [0.18513067, 0.18170803, 0.27007205]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3
# Every time we execute this, we get different set of numbers.

array([[0.35599872, 0.08673658, 0.36694492],
       [0.39738187, 0.8931959 , 0.86973786],
       [0.33151284, 0.87255103, 0.68912628],
       [0.517622  , 0.64043958, 0.53365491],
       [0.01276011, 0.68755756, 0.30891367]])

In [33]:
# Reproducible pseudo-random numbers by setting seed
np.random.seed(177)
random_array_4 = np.random.randint(0,10,(5,3))
random_array_4

# Every time we execute this, we get same set of numbers for a fixed seed.

array([[1, 7, 6],
       [4, 1, 5],
       [9, 2, 4],
       [4, 7, 9],
       [8, 1, 6]])

# Viewing Arrays and Matrices